### ISSUE TITLE
Implement backpack weight-checking modules

### ISSUE THREAD

**Issue by Parker8283** [Parker8283/IguanaTweaks#29]
This is issue #20 as an enhancement/checklist thingy.
- [ ] ~~Eydamos's Backpack Mod~~ His code is broken pretty bad.
- [ ] Forestry
- [ ] Tinker's Construct
- [ ] copygirl's Better Storage
- [ ] Backpacks by Brad
- [ ] More Backpacks Forestry addon
- [ ] Aroma1997's Better Chests (?)
- [ ] LordDusk's Bagginess (heh)
- [ ] Thermal Expansion
- [ ] Extra Utilities

If there's more, let me know. This issue will probably stay open for a while.

**Comment by Adaptivity** [comment]
How much time it will take to code plugins for Tinker's Construct and Eydamos's Backpacks? Really need these.

**Comment by Parker8283** [comment]
Harder for Eydamos's because it isn't open source (as far as I can tell). Will see if I have time to get this started soon.

**Comment by Adaptivity** [comment]
You will be surprised but it's open source: https://github.com/Eydamos/Minecraft-Backpack-Mod :smile:

**Comment by Parker8283** [comment]
Well I'm just blind.

**Comment by Parker8283** [comment]
Ok, so...Eydamos's code is broken beyond repair. I just spent the last couple hours trying to make it work, and there are things that just...aren't...so for now, no module for Eydamos's.

**Comment by SynergiAios** [comment]
Another mod occured with a Backpack not recognized via Iguana Tweaks - The Camping mod 

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1286831-the-camping-mod-2-2e
