### ISSUE TITLE
maxCarryWeight can't be set below 512

### ISSUE THREAD

**Issue by necanthrope** [Parker8283/IguanaTweaks#32]
Greetings, and thank you for an excellent mod :)

I'm trying to configure the maxCarryWeight property to be a value below 512, in this case 64.  If I stop my server, set the value to 64, and then restart it, the max carry weight listed in F3 is still 512.  The config file value doesn't change, so it's as if it's ignoring it.

I'll happily include my config file, but it's the one generated by the mod.  I'm running this mod file:
IguanaTweaks-1.7.10-Beta-19.jar

**Comment by drago87** [comment]
is having the same problem. also using beta-19 well i hope you get it sorted loving it

**Comment by Parker8283** [comment]
The weight system should be less derpy in the repo. Need to do a few more tests before making a build.

**Comment by necanthrope** [comment]
The problem I was having is that in server scenarios, the mod was ignoring the server config and using its own.  That's a problem for the server I am running.  I have a functional fix for it, where if it's in a remote server situation, it sends a message to the client with the config data.  Are you interested in a push request with this functionality?

**Comment by Parker8283** [comment]
A good server mod pack makes sure that the configs on both sides are the same. Anyways, I can't stop you making a pull request.

**Comment by necanthrope** [comment]
Yeah, but if you're not interested, there's no point in making one. :)

In the environment you describe (making sure the configs match), what should the system do if there's a discrepancy?  What config takes precedence?

**Comment by Parker8283** [comment]
Generally, the servers should. Because if the clients did, then they could just revert all the tweaks made. It should be the servers that takes precedence. However, you don't want to change the content of the clients config files through code when they connect to a server. I do know how to implement this properly, though a PR would help, as makes less work for me :P

**Comment by necanthrope** [comment]
Oh, well that's perfect then; the change I put in doesn't alter the local config if it's different, it just ignores it in favor of the server config. Looks like we're on the same page after all.

**Comment by Parker8283** [comment]
Ok, so the maxCarryWeight is fine, but I believe that this issue is more of "Server config isn't syncing to Client." I will open up a new issue on that.
