### ISSUE TITLE
Better Encumbrance

### ISSUE THREAD

**Issue by earthcrafterman** [Parker8283/IguanaTweaks#33]
I personally loved the idea of encumbrance when I saw it, however I was quite disappointed when I found it didn't actually limit a player's inventory, only slowing them down for it. I always imagined that the player's inventory wouldn't accept any more items that would make it go over the threshold, thus limiting their inventory considerably. What I got however was an inventory that would only slow you down the more you carried, and then stopped slowing you down altogether when it got to a certain point.

What I suggest is the addition of two config options:
1. MaxWeightLimit: A boolean that stops you from carrying any items that would put you over the max weight
2. MaxWeightSlowdown: A boolean that multiplies the slowdown from weight by a configurable amount after passing the max weight

Thank you for your time

**Comment by WolfieWaffle** [comment]
I agree with this, I think it would be helpful in hardcore packs, as well as just in general. It also bothers me that you can carry a full inventory of items with little effect, which I described in my other issue, #43. I would like to see this.

**Comment by WolfieWaffle** [comment]
Just one thing, I think the config options wouldn't be boolean, IIRC a boolean is true or false. You would probably want a double.
