### ISSUE TITLE
Disable Weight Tooltip

### ISSUE THREAD

**Issue by Nentify** [Parker8283/IguanaTweaks#37]
It'd be nice if we could have an option to disable weight tooltips on blocks and items.

Thanks!

**Comment by Parker8283** [comment]
Just don't have F3+H on for the time being. It's a debug thing anyway.

**Comment by Nentify** [comment]
Oh, I didn't realise F3 + H caused that, aha. Should probably turn that off
 Thanks!
On 10 Feb 2015 14:16, Parker Young <notifications@github.com> wrote:Just don't have F3+H on for the time being. It's a debug thing anyway.

**Comment by Parker8283** [comment]
I'll probably add a config option at some point anyways.
