### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Adaptivity** [Parker8283/IguanaTweaks#42]
http://pastebin.com/f9bXcYRU
How to reproduce:
1) Install mod, start the game.
2) Leave the game.
3) Try start the game again.
4) Get crash.
5) Remove Iguana Tweaks config (Just default config)
6) You can start the game again.
Tested on Java 8, Forge 1378, Iguana Tweaks 2A
Mods installed: http://i.imgur.com/zC39a5R.jpg
Also reported on forums: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1295224-1-7-10-iguana-tweaks?comment=165

**Comment by Parker8283** [comment]
I can't reproduce this, but I may have a clue as to what's happening.

**Comment by Parker8283** [comment]
Try the [latest snapshot build](https://drone.io/github.com/Parker8283/IguanaTweaks/files) and see if it fixes it. Considering I can't reproduce this, this is the only thing that I can think of that would be causing this problem.

**Comment by Adaptivity** [comment]
Solved. Thanks.

**Comment by Parker8283** [comment]
Actually, just noticed something. Next snapshot will ACTUALLY fix it. Don't know how the last one was working for you...but yea...
