### ISSUE TITLE
Jumping Limitations

### ISSUE THREAD

**Issue by MagicianDC** [Parker8283/IguanaTweaks#44]
I love the weighted system; I see all my greedy players slowly walking up to our castle in the sky, it's pretty funny! However, recently, I've been noticing that players started to build cart systems, which is exactly what this mod was trying to accomplish- I loved it. But now, one player managed to bypass all that this mod has been trying to do with the weighing down players with heavy inventories... he jumped! By jumping, one may easily attain almost normal speed again, and even skip all the necessity of trying to build a complex train station. Players now continuously jump on my server; its like watching bunnies and frogs jumping everywhere- it's pretty annoying. It got to the point, regardless if a player had been weigh down or not, they all just jump by way of travel now since it bypasses your weighted system. My request is, can you make it so players jump height is affected by weight? Perhaps, just don't allow players to jump at all when their weight has been encumbered, therefore, forcing players back to using carts or suffer a slow walks back home. Please, consider this suggestion and stop all the jumping frogs on my server. I also want players who have been encumbered to not be able to move at all until they release some of their load (for some reason, I thought this mod used to do that, but now, even a highly encumbered player is still able to move the same speed as an encumbered player).

Thanks for your time-

DC

**Comment by WolfieWaffle** [comment]
Agree, I feel like there are multiple problems with the weight system, including this one. Others include #43 and #33
