### ISSUE TITLE
[Question] Drone.io builds

### ISSUE THREAD

**Issue by WolfieWaffle** [Parker8283/IguanaTweaks#46]
I don't really want to put this here, since it's not an issue, but I can't find where else to ask questions on GitHub. Basically, I see a bunch of snapshots on drone.io, but only one has a download. I want the latest snapshot, so does that mean I would have to compile it myself, or is there a link somewhere?

Sorry if this is the wrong place to ask this, in fact I'm pretty sure it is, but again, GitHub seems to have no questions section.

**Comment by Parker8283** [comment]
The latest snapshots are always available from drone.io. I don't understand you question past that.

**Comment by WolfieWaffle** [comment]
I mean to get the latest snapshots, that I can put in the mods folder, do I have to compile them by using some sort of snapshot url, or is there just a download link somewhere. I could only find one download link, and it doesn't look like the latest version.

**Comment by Parker8283** [comment]
The link on the MCForums has the link for the downloads for the latest snapshot. It is automatically built when a change is made to the repo. I can check real quick, but it should be the latest.

**Comment by WolfieWaffle** [comment]
OK, so the one download link is constantly updated, not a new link for every new build.

**Comment by Parker8283** [comment]
Go to the link. Snapshot 4 is the latest.

**Comment by WolfieWaffle** [comment]
Thanks, I guess I just got confused or something :P
