### ISSUE TITLE
Crash with nether ores or thermal foundation

### ISSUE THREAD

**Issue by Mustang351c** [Parker8283/IguanaTweaks#49]
When using this mod alongside netherores or thermal foundation i get a crash on loading

at iguanaman.iguanatweaks.config.IguanaWeightsConfig.getWeight(IguanaWeightsConfig.java:46)
at iguanaman.iguanatweaks.util.StackSizeTweaks.init(StackSizeTweaks.java:47)
at iguanaman.iguanatweaks.IguanaTweaks.postInit(IguanaTweaks.java:102)

disabling the stacksize divider (setting them all to 1) fixes this. I am using 1.7.10-2A, as it is the only version available on curseforge.

**Comment by Parker8283** [comment]
Please pastebin the full crash report. This helps me none.

**Comment by Mustang351c** [comment]
http://pastebin.com/sVBPTVrs

This is with all my current mods installed, but disabling nether ores or the stack size divider fixes the crash.

**Comment by Parker8283** [comment]
They the [latest snapshot build](https://drone.io/github.com/Parker8283/IguanaTweaks/files). I'm pretty sure this is the same bug that I fixed a while ago, but I can't tell for sure.

**Comment by Mustang351c** [comment]
Ill try that and see if it fixes it. I am making my modpack for the curse voice launcher and am restricted to the files available on curse for the modpack.

**Comment by Parker8283** [comment]
If the snapshot build indeed fixes it, I'll release 2B on CF later today for you. It has a couple other fixes and a new config option, so it's probably worth it.

**Comment by Mustang351c** [comment]
That fixed the crash. Thanks for the CF upload in advance, and sorry about the partial crash report. That's all I had left of an old crash report so I reproduced the crash and got a new one.

**Comment by Parker8283** [comment]
Look for it on CF towards the end of the day.
