### ISSUE TITLE
Bed Spawning

### ISSUE THREAD

**Issue by vivagabe** [Parker8283/IguanaTweaks#51]
Im trying to allow beds to set spawn, break on respawn, but NOT allow sleeping.
These are my settings:

respawn {
    # The players bed will be destroyed upon respawning
    B:destroyBedOnRespawn=true

```
# If active using a bed will not set your spawn point (requires disableSleeping to be true)
B:disableSettingSpawn=false

# Disable sleeping, spawn can still be set with a bed
B:disableSleeping=true

# Amount of health you respawn with (with 'respawnHealthDifficultyScaling' this will be 
```

modified by difficulty)
    I:respawnHealth=10

```
# Is the amount of health you respawn with dependant on difficulty?
B:respawnHealthDifficultyScaling=true

# Exactly where you respawn (after death) is randomised around the spawn point (either to a bed 
```

or original spawn point), upto a maximum of this many blocks away (set to 0 to disable)
    I:respawnLocationRandomisationMax=800

```
# Exactly where you respawn (after death) is randomised around the spawn point (either to a bed 
```

or original spawn point), at least a minimum of this many blocks away (set to 0 to disable)
    I:respawnLocationRandomisationMin=100

```
# Exactly where you spawn (upon login) is randomised around the spawn point, upto a maximum of 
```

this many blocks away (set to 0 to disable)
    I:spawnLocationRandomisationMax=0

```
# Exactly where you spawn (upon login) is randomised around the spawn point, at least a minimum 
```

of this many blocks away (set to 0 to disable)
    I:spawnLocationRandomisationMin=0
}

I have it set this way but I'm still not respawning at my bed.  Any ideas?

**Comment by Parker8283** [comment]
Pastebin your entire config. GH's formatting makes it hard for me to read this.

**Comment by vivagabe** [comment]
https://gist.github.com/vivagabe/4c9eba85a30fd8d96107

Sorry if i did this wrong, I've never Gist before :X.
