### ISSUE TITLE
[Suggestion] Add blocks to terrain groups via config

### ISSUE THREAD

**Issue by BlocklockCity** [Parker8283/IguanaTweaks#53]
I noticed Plant Mega Pack plants don't count as "plants" to the "Percentage of slowdown when walking through plants" option.  If possible, it'd be nice to be able to set custom slowdown for any block added to a given config file, but I don't know 1.) how difficult this would be to implement, or 2.) how many people would actually use this feature.  Being able to add blocks to the existing "terrain groups" would be enough for most people who want to do something like this, I think.

**Comment by Parker8283** [comment]
Terrain groups are based on the block's material. So those blocks don't have the material set to plants.

Either that or I'm completely wrong.
