### ISSUE TITLE
weights.json doesn't have support for metadata

### ISSUE THREAD

**Issue by Suterusu1337** [Parker8283/IguanaTweaks#54]
I am trying to add GregTech items into weights.json.

GregTech has very few item IDs as most of the items are stored in NBT as damage values:

gregtech:gt.blockmachines
gregtech:gt.blockores

This makes it difficult to add weights for a tin wire versus a plasma generator control block (they would differ in weights by a lot...)

I've tried adding the damage value to the end, gregtech:gt.blockmachines:1240, but this does not work as expected.

Ignoring the first few values here that I was testing with, here is the current conifg: https://github.com/Suterusu1337/Custom-Mod-Pack/blob/master/config/IguanaTweaks/weights.json

Again, I've tried adding the damage values to the ends of the blocks but it does not work.  This would be like wanting vanilla wool to all weigh a different amount.

Am I doing it wrong or is this a feature request?

**Comment by Parker8283** [comment]
Wat, I don't have support for metadata? Bad Parker! Will fix when I have access to a dev env.

As for nbt, well, that's a lot harder. I can't really think of a way to implement this cleanly right now, but maybe something will come up. Still, I wouldn't hold your breath.

**Comment by Suterusu1337** [comment]
Would be awesome to be able to do weights for things like Greg Tech (at which it could support any mod).

How well do you think the mod will run when I add 10K+ weights into the config?
