### ISSUE TITLE
Fly speed disproportionately affected by weight/encumbrance...

### ISSUE THREAD

**Issue by Twilight13** [Parker8283/IguanaTweaks#55]
Summary:
Weight/Encumbrance slowdown affects flying speed _much_ more strongly than walking speed. Carrying even a single stack or two of blocks can more than halve your regular flying speed.

I use Iguana Tweaks for a variety of things, but one of the most fun for me is the weight system, where you move more slowly the more you carry. It's adjustable, and works well. However, I am using the Survival Wings mod, which lets you craft wings that let you fly for a limited time (Until their durability runs out), and I've noticed that the weight slowdown is very out of balance for flying.

For example, if carrying almost nothing, the flight speed is as it should be, but carrying a single stack of cobblestone (16, in this case, as I've limited the stack sizes as well), it cuts the flying speed almost in half. Another stack or two of cobblestone and flying is slower than walking.

I don't mind slowdown for flying because of weight, just like with walking, but it doesn't scale the way that the walking slowdown does. I'm wondering if this is because it increases your drag/resistance, which slows you down somewhat while walking, but much more so while flying.

Is there anything that can be done about this? Just increasing the fly speed doesn't help, because even if I got it to the right speed while weighted down a bit, then the unencumbered fly speed would be crazy fast.

Thanks for any help in advance!

**Comment by WolfieWaffle** [comment]
I can confirm this also happens with jetpack type mods and it's very annoying.

**Comment by NedSer145** [comment]
How did you limit the stack size? And how to set it back to 64? Help me, I'm stuck with 16 O_O

**Comment by Twilight13** [comment]
There's a StackSizes section in the IguanaTweaks config file, where you can set in general how much stacksizes are reduced, although it's still based on their weight, I think. If you want to individually tweak stack sizes, you can use the SquidUtils mod, (http://mods.curse.com/mc-mods/minecraft/226025-squidutils-modpack-utility).

SquidUtils lets you change settings for individual items/blocks like stack sizes (Let potions stack, for example, or limit dirt to 7 block stacks, whatever), armor values, food values, durability limits, and so forth. Highly recommended for extensive customizing.
