### ISSUE TITLE
Nether Ores keeps crashing!

### ISSUE THREAD

**Issue by NedSer145** [Parker8283/IguanaTweaks#56]
As soon as I get Nether Ores in my mods file, it keeps crashing! As soon as I take it out, it's fine! How do I fix this? And yes, I am using 1.7.10 AND the snapshot-8. Also, how do I change the stacks so everything can be 64? Not 16 or something like that, because I have no idea how to change the max stack.

**Comment by Parker8283** [comment]
Please upload a crash report to pastebin or gist and link it here.

**Comment by NedSer145** [comment]
Uhh.. so nevermind. It works now. I just downloaded Nether Ores at 9minecraft and it apparently was an outdated version... feel free to close this, but can you still explain how to set back items to stack only 64? I'm dying with the 16 stacked cobblestone.
