### ISSUE TITLE
Encumbrance needs some work

### ISSUE THREAD

**Issue by Adarcer** [Parker8283/IguanaTweaks#58]
Hi parker like the mod but i don't use all the features also i hope this is in the right place when i did the google its said you were the maintainer for the 1.7+ version of the mod. I do like the idea of encumbrance but don't like stack size adjustments (unless there inventory only)  so i disabled that. anyways too get to the point carrying basic stuff and one stack of cobble (64 so 4 split up stacks) at default max weight = encumbered so i when into config raised max weight to 750
(extra 238 weight units) closed minecraft and completely relaunched. note i had put the cobble away before closing minecraft. when back in game I picked up the cobble again and i was still encumbered.

so what i suggest is some config options to go along with the max weight config that sets when you reach the weight thresholds. this would be handy for people who want to raise or lower the max weight
eg 
I:maxCarryWeight=512
I:EncumberedAt=200
I:EncumberedSlowdown=0.05 (5%)
etc to
I:Unmobile=512 <-- 0 to disable
I:UnmobileSlowdown=1.0  (100%)

Also love the step assist have you thought of releasing that as a standalone mod for people who don't
want to deal with inventory management so much

**Comment by WolfieWaffle** [comment]
I support this, the encumbrance mechanic right now is very... cumbersome.
But really, it does need work.
